---
name: "tsc Check"
description: "🛡️🐶 GitHub Action to check TypeScript errors with tsc and ReviewDog, enforcing error thresholds and incremental type safety."
inputs:
  reviewdog-version:
    description: "Version of ReviewDog to use"
    required: false
    default: "latest"
  typescript-version:
    description: "Version of the TypeScript npm package to use"
    required: false
    default: "latest"
  workdir:
    description: |
      Working directory relative to the root directory.
      This is where the action will look for a
      package.json which declares typescript as a dependency.
      Default is `.`.
    default: "."
    required: false
  high-water-mark:
    description: |
      The high-water mark for the number of errors to allow.
      If the number of errors is greater than this value, the action will fail.
      Default is `0`.
    default: "0"
    required: false
  help-doc-url:
    description: |
      URL to the help documentation for this action, if you wish to provide your own.
      This will be used in the action's failure message.
      Default is `https://github.com/lowlydba/tsc-check/blob/main/docs/find-tsc-regressions.md`
    default: "https://github.com/lowlydba/tsc-check/blob/main/docs/find-tsc-regressions.md"
  ### Flags for reviewdog ###
  level:
    description: |
      Report level for reviewdog [info,warning,error].
      Default is `error`.
    default: "error"
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-check,github-pr-review].
      Default is `github-pr-check`.
    default: "github-pr-check"
    required: false
  filter-mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `added`.
    default: "added"
    required: false
  fail-on-error:
    description: |
      Exit code for reviewdog when errors are found [true,false].
      Default is `false`.
    default: "false"
    required: false
  reviewdog-flags:
    description: |
      Additional reviewdog flags.
      Default is ``.
    default: ""
    required: false
  tool-name:
    description: "Tool name to use for reviewdog reporter"
    default: "tsc"
    required: false
  ### Flags for tsc ###
  tsc-flags:
    description: |
      Flags and args to pass to tsc.
      Default is `--noEmit --skipLibCheck`.
    default: "--noEmit --skipLibCheck"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install reviewdog
      uses: reviewdog/action-setup@v1.2.1
      with:
        reviewdog_version: ${{ inputs.reviewdog-version }}

    - name: Install TypeScript
      shell: bash
      run: |
        echo "::group::⬇️ Installing tsc"
        npm install typescript@${{ inputs.typescript-version }} -g --no-cache --no-audit --fund=false --loglevel=error --no-update-notifier
        version=$(tsc --version)
        echo "::debug::tsc version $version installed"
        echo "::endgroup::"

    - name: tsc check
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter-mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog-flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool-name }}
        INPUT_TSC_FLAGS: ${{ inputs.tsc-flags }}
        INPUT_HIGH_WATER_MARK: ${{ inputs.high-water-mark }}
        INPUT_HELP_DOC_URL: ${{ inputs.help-doc-url }}